# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/qcom-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/zte/qcom-common/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
    vendor/zte/qcom-common/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/zte/qcom-common/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/zte/qcom-common/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/zte/qcom-common/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/zte/qcom-common/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/zte/qcom-common/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/zte/qcom-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/zte/qcom-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/zte/qcom-common/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/zte/qcom-common/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/zte/qcom-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/zte/qcom-common/proprietary/vendor/lib/libWVphoneAPI.so:system/vendor/lib/libWVphoneAPI.so \
    vendor/zte/qcom-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/zte/qcom-common/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
    vendor/zte/qcom-common/proprietary/etc/firmware/dxhdcp2.b00:system/etc/firmware/dxhdcp2.b00 \
    vendor/zte/qcom-common/proprietary/etc/firmware/dxhdcp2.b01:system/etc/firmware/dxhdcp2.b01 \
    vendor/zte/qcom-common/proprietary/etc/firmware/dxhdcp2.b02:system/etc/firmware/dxhdcp2.b02 \
    vendor/zte/qcom-common/proprietary/etc/firmware/dxhdcp2.b03:system/etc/firmware/dxhdcp2.b03 \
    vendor/zte/qcom-common/proprietary/etc/firmware/dxhdcp2.mdt:system/etc/firmware/dxhdcp2.mdt \
    vendor/zte/qcom-common/proprietary/etc/DxHDCP.cfg:system/etc/DxHDCP.cfg \
    vendor/zte/qcom-common/proprietary/etc/hdcp_8960.dat.enc:system/etc/hdcp_8960.dat.enc \
    vendor/zte/qcom-common/proprietary/lib/libDxHdcp.so:system/lib/libDxHdcp.so \
    vendor/zte/qcom-common/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/zte/qcom-common/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/zte/qcom-common/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/zte/qcom-common/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/zte/qcom-common/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/zte/qcom-common/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/zte/qcom-common/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/zte/qcom-common/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/zte/qcom-common/proprietary/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
    vendor/zte/qcom-common/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/zte/qcom-common/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/zte/qcom-common/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/zte/qcom-common/proprietary/lib/libOmxAmrwbplusDec.so:system/lib/libOmxAmrwbplusDec.so \
    vendor/zte/qcom-common/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/zte/qcom-common/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/zte/qcom-common/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/zte/qcom-common/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/zte/qcom-common/proprietary/bin/aplogd:system/bin/aplogd \
    vendor/zte/qcom-common/proprietary/bin/dbvc_atvc_property_set:system/bin/dbvc_atvc_property_set \
    vendor/zte/qcom-common/proprietary/bin/hardware_revisions.sh:system/bin/hardware_revisions.sh \
    vendor/zte/qcom-common/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/zte/qcom-common/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/zte/qcom-common/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/zte/qcom-common/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/zte/qcom-common/proprietary/bin/bootmodem:system/bin/bootmodem \
    vendor/zte/qcom-common/proprietary/bin/efsks:system/bin/efsks \
    vendor/zte/qcom-common/proprietary/bin/ks:system/bin/ks \
    vendor/zte/qcom-common/proprietary/bin/qcks:system/bin/qcks \
    vendor/zte/qcom-common/proprietary/bin/radish:system/bin/radish \
    vendor/zte/qcom-common/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/zte/qcom-common/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/zte/qcom-common/proprietary/lib/libadropbox.so:system/lib/libadropbox.so \
    vendor/zte/qcom-common/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/zte/qcom-common/proprietary/lib/libTimeService.so:system/lib/libTimeService.so \
    vendor/zte/qcom-common/proprietary/etc/firmware/cyttsp_8064_mtp.hex:system/etc/firmware/cyttsp_8064_mtp.hex \
    vendor/zte/qcom-common/proprietary/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
    vendor/zte/qcom-common/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/zte/qcom-common/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/zte/qcom-common/proprietary/bin/ftmipcd:system/bin/ftmipcd \
    vendor/zte/qcom-common/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/zte/qcom-common/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/zte/qcom-common/proprietary/lib/libxml.so:system/lib/libxml.so
